spring:
  application:
    name: wjp-ai-code-user
  # session
  session:
    store-type: redis
    # 30 days expire
    timeout: 2592000
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/w_ai_coder_mother
    username: root
    password: 123456
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password:
# 当前服务的端口
server:
  port: 8124
  servlet:
    context-path: /api
    # 30 days expire
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.wjp.waicodeuser.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
